import { ArchiveRestore, BedDouble, Edit3, Plus, PowerOff } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { api } from '../services/api';
import type { Bed } from '../types';

const empty={name:'',sector:'Internação',notes:''};
function errorMessage(error:unknown){const e=error as {response?:{data?:{message?:string}}};return e.response?.data?.message??'Não foi possível concluir a operação.'}
export function BedsPage(){const[beds,setBeds]=useState<Bed[]>([]);const[editing,setEditing]=useState<Bed|null|undefined>(undefined);const[form,setForm]=useState(empty);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
const load=useCallback(()=>{setLoading(true);api.get<Bed[]>('/beds').then(r=>setBeds(r.data)).catch(()=>setError('Não foi possível carregar os leitos.')).finally(()=>setLoading(false))},[]);useEffect(()=>{load()},[load]);
function open(b?:Bed){setEditing(b??null);setError('');setForm(b?{name:b.name,sector:b.sector,notes:b.notes??''}:empty)}
async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{editing?await api.put(`/beds/${editing.id}`,form):await api.post('/beds',form);setEditing(undefined);load()}catch(err){setError(errorMessage(err))}finally{setLoading(false)}}
async function toggle(b:Bed){if(!confirm(`${b.active?'Inativar':'Reativar'} o leito ${b.name}?`))return;try{await api.patch(`/beds/${b.id}/${b.active?'deactivate':'reactivate'}`);load()}catch(err){setError(errorMessage(err))}}
const sectors=[...new Set(beds.map(b=>b.sector))];return <><div className="page-heading"><div><p className="eyebrow">ESTRUTURA DA CLÍNICA</p><h1>Leitos</h1><p className="muted">Gerencie disponibilidade, setores e ocupação dos leitos.</p></div><button className="primary-button button-with-icon" onClick={()=>open()}><Plus/>Novo leito</button></div>{error&&editing===undefined&&<div className="form-error">{error}</div>}{loading&&!beds.length?<div className="state-card loading-state">Carregando leitos...</div>:<div className="bed-sectors">{sectors.map(sector=><section className="panel" key={sector}><div className="panel-header"><div><h2>{sector}</h2><p>{beds.filter(b=>b.sector===sector).length} leito(s)</p></div></div><div className="bed-grid">{beds.filter(b=>b.sector===sector).map(b=><article className={`bed-card ${b.currentHospitalization?'occupied':'available'} ${!b.active?'disabled':''}`} key={b.id}><header><span className="bed-icon"><BedDouble/></span><div><h3>{b.name}</h3><p>{b.active?(b.currentHospitalization?'Ocupado':'Disponível'):'Inativo'}</p></div></header>{b.currentHospitalization?<div className="bed-patient"><span>Paciente atual</span><strong>{b.currentHospitalization.animal.name}</strong></div>:<div className="bed-patient"><span>{b.notes||'Pronto para receber paciente'}</span></div>}<footer><button className="icon-button" onClick={()=>open(b)} title="Editar"><Edit3/></button><button className="ghost-button button-with-icon" onClick={()=>toggle(b)}>{b.active?<PowerOff/>:<ArchiveRestore/>}{b.active?'Inativar':'Reativar'}</button></footer></article>)}</div></section>)}</div>}{editing!==undefined&&<Modal title={editing?'Editar leito':'Novo leito'} subtitle="Identifique o leito e o setor da clínica." onClose={()=>setEditing(undefined)}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nome do leito *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: UTI-02"/></label><label>Setor *<input required value={form.sector} onChange={e=>setForm({...form,sector:e.target.value})} placeholder="Ex.: UTI"/></label><label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<footer className="form-footer"><button type="button" className="ghost-button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-button" disabled={loading}>{loading?'Salvando...':'Salvar leito'}</button></footer></form></Modal>}</>}
