import { FileHeart, FileText, Mail, MapPin, PawPrint, Phone, Pill, Printer, Search, Stethoscope } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { useClinicSettings } from '../contexts/ClinicSettingsContext';

type Option={id:string;status:string;admittedAt:string;dischargedAt:string|null;animal:{name:string;species:string;breed:string|null;tutor:{name:string;phone:string}};bed:{name:string;sector:string}|null};
type DocData={settings:any;hospitalization:any};
type DocType='admission'|'prescription'|'discharge'|'record';
const labels:Record<DocType,string>={admission:'Ficha de internação',prescription:'Prescrição médica',discharge:'Relatório de alta',record:'Prontuário clínico'};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';

export function DocumentsPage(){
 const {settings}=useClinicSettings(); const[options,setOptions]=useState<Option[]>([]);const[selected,setSelected]=useState('');const[data,setData]=useState<DocData|null>(null);const[type,setType]=useState<DocType>('admission');const[search,setSearch]=useState('');const[error,setError]=useState('');
 useEffect(()=>{api.get('/documents/options').then(r=>{setOptions(r.data);if(r.data[0])setSelected(r.data[0].id)}).catch(()=>setError('Não foi possível carregar os pacientes.'))},[]);
 useEffect(()=>{if(!selected){setData(null);return}api.get(`/documents/hospitalizations/${selected}`).then(r=>{setData(r.data);setError('')}).catch(()=>setError('Não foi possível gerar o documento.'))},[selected]);
 const filtered=useMemo(()=>options.filter(o=>`${o.animal.name} ${o.animal.tutor.name}`.toLowerCase().includes(search.toLowerCase())),[options,search]);
 const h=data?.hospitalization; const clinic=data?.settings??settings;
 function print(){window.print()}
 return <><div className="page-heading print-hidden"><div><p className="eyebrow">DOCUMENTAÇÃO CLÍNICA</p><h1>Documentos e fichas</h1><p className="muted">Gere documentos preenchidos automaticamente com os dados da internação.</p></div><button className="primary-button button-with-icon" disabled={!data} onClick={print}><Printer/>Imprimir / Salvar PDF</button></div>
 <div className="documents-layout print-hidden"><aside className="panel documents-sidebar"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Paciente ou tutor"/></div><div className="document-patients">{filtered.map(o=><button className={selected===o.id?'active':''} key={o.id} onClick={()=>setSelected(o.id)}><strong>{o.animal.name}</strong><span>{o.animal.tutor.name}</span><small>{o.dischargedAt?'Alta realizada':o.bed?`${o.bed.sector} • ${o.bed.name}`:'Internado'}</small></button>)}</div></aside>
 <section className="panel documents-main"><div className="document-type-grid"><button className={type==='admission'?'active':''} onClick={()=>setType('admission')}><FileHeart/><strong>Internação</strong><span>Ficha de entrada</span></button><button className={type==='prescription'?'active':''} onClick={()=>setType('prescription')}><Pill/><strong>Prescrição</strong><span>Tratamento prescrito</span></button><button className={type==='discharge'?'active':''} onClick={()=>setType('discharge')}><FileText/><strong>Alta</strong><span>Resumo de alta</span></button><button className={type==='record'?'active':''} onClick={()=>setType('record')}><Stethoscope/><strong>Prontuário</strong><span>Histórico clínico</span></button></div>{error&&<div className="form-error">{error}</div>}</section></div>
 {h&&<article className="clinical-document" id="clinical-document"><header className="document-header"><div className="document-brand">{clinic?.logoDataUrl?<div className="document-logo-mark"><img src={clinic.logoDataUrl} alt={`Logo ${clinic?.name||'PetLife'}`}/></div>:<div className="document-logo-mark document-logo-fallback"><PawPrint aria-hidden="true"/></div>}<div className="document-brand-copy"><h2>{clinic?.name||'PetLife'}</h2><p>{clinic?.legalName||'Clínica Veterinária'}</p><div className="document-contact-row">{clinic?.phone&&<span><Phone/> {clinic.phone}</span>}{clinic?.email&&<span><Mail/> {clinic.email}</span>}{[clinic?.city,clinic?.state].filter(Boolean).length>0&&<span><MapPin/> {[clinic?.city,clinic?.state].filter(Boolean).join(' - ')}</span>}</div></div></div><div className="document-title-block"><strong>{labels[type]}</strong><span>Emitido em {new Date().toLocaleString('pt-BR')}</span></div></header>
 <div className="document-clinic-line">{[clinic?.cnpj,clinic?.address].filter(Boolean).join('  |  ')}</div>
 <section className="document-patient"><h3>Paciente e internação</h3><div className="document-info-grid"><p><span>Paciente</span><b>{h.animal.name}</b></p><p><span>Espécie / raça</span><b>{h.animal.species}{h.animal.breed?` • ${h.animal.breed}`:''}</b></p><p><span>Tutor</span><b>{h.animal.tutor.name}</b></p><p><span>Contato</span><b>{h.animal.tutor.phone||'—'}</b></p><p><span>Entrada</span><b>{fmt(h.admittedAt)}</b></p><p><span>Veterinário</span><b>{h.veterinarian||'Não informado'}</b></p><p><span>Leito</span><b>{h.bed?`${h.bed.sector} • ${h.bed.name}`:'Sem leito'}</b></p><p><span>Prioridade</span><b>{h.priority}</b></p></div></section>
 {type==='admission'&&<><DocSection title="Motivo da internação" text={h.reason}/><DocSection title="Diagnóstico / hipótese diagnóstica" text={h.diagnosis||'Não informado'}/><DocSection title="Observações" text={h.notes||'Sem observações.'}/></>}
 {type==='prescription'&&<section className="document-section"><h3>Prescrições</h3>{h.prescriptions.length===0?<p>Nenhuma prescrição registrada.</p>:<table><thead><tr><th>Medicamento</th><th>Dose</th><th>Via</th><th>Frequência</th><th>Responsável</th></tr></thead><tbody>{h.prescriptions.map((p:any)=><tr key={p.id}><td>{p.medication}</td><td>{p.dose} {p.unit}</td><td>{p.route}</td><td>A cada {p.frequencyHours}h</td><td>{p.responsible||h.veterinarian||'—'}</td></tr>)}</tbody></table>}</section>}
 {type==='discharge'&&<><DocSection title="Diagnóstico" text={h.diagnosis||'Não informado'}/><DocSection title="Resumo de alta" text={h.dischargeSummary||(h.dischargedAt?'Sem resumo registrado.':'Alta ainda não realizada.')}/><div className="document-info-grid"><p><span>Data da alta</span><b>{fmt(h.dischargedAt)}</b></p><p><span>Previsão de alta</span><b>{fmt(h.expectedDischargeAt)}</b></p></div></>}
 {type==='record'&&<section className="document-section"><h3>Histórico clínico</h3><div className="document-record-list">{[...h.clinicalEvents.map((e:any)=>({date:e.eventAt,title:e.title,text:e.description,responsible:e.responsible})),...h.procedures.map((p:any)=>({date:p.completedAt||p.scheduledAt,title:`Procedimento: ${p.title}`,text:p.description||p.notes,responsible:p.responsible})),...h.medicationDoses.filter((d:any)=>d.status==='ADMINISTERED').map((d:any)=>({date:d.administeredAt||d.scheduledAt,title:`Medicação: ${d.medication} ${d.dose||''} ${d.unit||''}`,text:d.notes,responsible:d.administeredBy}))].sort((a:any,b:any)=>new Date(a.date).getTime()-new Date(b.date).getTime()).map((e:any,i:number)=><div key={i}><time>{fmt(e.date)}</time><div><strong>{e.title}</strong>{e.text&&<p>{e.text}</p>}<small>{e.responsible||'Responsável não informado'}</small></div></div>)}</div></section>}
 <footer className="document-signatures"><div><span>________________________________________</span><strong>{h.veterinarian||'Médico(a) Veterinário(a)'}</strong><small>Responsável pelo atendimento</small></div><div><span>________________________________________</span><strong>{h.animal.tutor.name}</strong><small>Tutor(a) / responsável</small></div></footer><div className="document-footer">{clinic?.name||'PetLife'} • {clinic?.tagline||'Gestão veterinária'}</div></article>}</>}
function DocSection({title,text}:{title:string;text:string}){return <section className="document-section"><h3>{title}</h3><p>{text}</p></section>}
