import{ArrowDownCircle,ArrowUpCircle,Edit3,Plus,Search,Trash2,WalletCards}from'lucide-react';import{useCallback,useEffect,useState,type FormEvent}from'react';import{Modal}from'../components/Modal';import{api}from'../services/api';import type{FinanceStats,FinancialEntry}from'../types';
const empty={type:'INCOME',description:'',category:'Consulta',amount:0,status:'PAID',paymentMethod:'PIX',occurredAt:new Date().toISOString().slice(0,10),dueAt:'',paidAt:'',animalId:'',hospitalizationId:'',notes:''};const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const msg=(e:unknown)=>(e as any)?.response?.data?.message??'Não foi possível concluir.';
export function FinancePage(){const[items,setItems]=useState<FinancialEntry[]>([]),[stats,setStats]=useState<FinanceStats|null>(null),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[search,setSearch]=useState(''),[editing,setEditing]=useState<FinancialEntry|null|undefined>(undefined),[form,setForm]=useState<any>(empty),[error,setError]=useState('');
const load=useCallback(async()=>{try{const[a,b]=await Promise.all([api.get('/finance',{params:{month,search}}),api.get('/finance/stats',{params:{month}})]);setItems(a.data);setStats(b.data);setError('')}catch(e){setError(msg(e))}},[month,search]);useEffect(()=>{const t=setTimeout(()=>void load(),150);return()=>clearTimeout(t)},[load]);
function open(i?:FinancialEntry){setEditing(i??null);setForm(i?{...i,occurredAt:i.occurredAt.slice(0,10),dueAt:i.dueAt?.slice(0,10)??'',paidAt:i.paidAt?.slice(0,10)??'',animalId:i.animalId??'',hospitalizationId:i.hospitalizationId??'',notes:i.notes??'',paymentMethod:i.paymentMethod??''}:{...empty});setError('')}
async function submit(e:FormEvent){e.preventDefault();try{editing?await api.put(`/finance/${editing.id}`,form):await api.post('/finance',form);setEditing(undefined);await load()}catch(err){setError(msg(err))}}
async function remove(i:FinancialEntry){if(!confirm(`Excluir “${i.description}”?`))return;await api.delete(`/finance/${i.id}`);await load()}
return<><div className="page-heading"><div><p className="eyebrow">GESTÃO FINANCEIRA</p><h1>Financeiro</h1><p className="muted">Receitas, despesas e visão mensal da clínica.</p></div><button className="primary-button button-with-icon" onClick={()=>open()}><Plus/>Novo lançamento</button></div>
{stats&&<div className="mini-metrics"><article><ArrowUpCircle/><div><strong>{brl(stats.income)}</strong><span>Receitas pagas</span></div></article><article><ArrowDownCircle/><div><strong>{brl(stats.expense)}</strong><span>Despesas pagas</span></div></article><article><WalletCards/><div><strong>{brl(stats.balance)}</strong><span>Saldo do mês</span></div></article><article><WalletCards/><div><strong>{brl(stats.pending)}</strong><span>Pendentes</span></div></article></div>}
<section className="panel"><div className="toolbar toolbar-wrap"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamento"/></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>{error&&editing===undefined&&<div className="form-error">{error}</div>}<div className="finance-list">{items.map(i=><article className={`finance-row finance-${i.type.toLowerCase()}`} key={i.id}><div className="finance-sign">{i.type==='INCOME'?<ArrowUpCircle/>:<ArrowDownCircle/>}</div><div><strong>{i.description}</strong><span>{i.category} • {new Date(i.occurredAt).toLocaleDateString('pt-BR')}</span></div><b>{brl(i.amount)}</b><span className={`status ${i.status.toLowerCase()}`}>{i.status==='PAID'?'Pago':i.status==='PENDING'?'Pendente':'Cancelado'}</span><div className="row-actions"><button className="icon-button" onClick={()=>open(i)}><Edit3/></button><button className="icon-button danger-icon" onClick={()=>void remove(i)}><Trash2/></button></div></article>)}{!items.length&&<div className="empty-state"><WalletCards size={40}/><h3>Nenhum lançamento</h3></div>}</div></section>
{editing!==undefined&&<Modal title={editing?'Editar lançamento':'Novo lançamento'} subtitle="Registre entradas e saídas da clínica." onClose={()=>setEditing(undefined)} wide><form className="entity-form" onSubmit={submit}><div className="form-grid three-cols"><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="INCOME">Receita</option><option value="EXPENSE">Despesa</option></select></label><label className="full">Descrição *<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Categoria *<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Valor *<input required type="number" min=".01" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="PAID">Pago</option><option value="PENDING">Pendente</option><option value="CANCELED">Cancelado</option></select></label><label>Forma de pagamento<input value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}/></label><label>Data *<input required type="date" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/></label><label>Vencimento<input type="date" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="form-footer"><button type="button" className="secondary-button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-button">Salvar</button></div></form></Modal>}</>}
